name: EAS build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Create new build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v6
        with:
          eas-version: latest
          token: nLKsMtYTS3LvX9Q1Be8sbymKbiRcgIIx1gu63ND2
      - run: yarn install
      - run: eas build --profile preview --platform android